### ISSUE TITLE
Extension to record on the current tab

### ISSUE THREAD

**Issue by vinuvvk88** [carsonsaldanha/screen-recorder#1]
Right now we need to select a screen and that screen gets recorded. Is there a way to directly have "Record" button and the current screen will get recorded? Also anyway we can skip the top portion of the browser with URL from being recorded ?

**Comment by carsonsaldanha** [comment]
> Right now we need to select a screen and that screen gets recorded. Is there a way to directly have "Record" button and the current screen will get recorded? 

The screen capture API doesn't allow that behavior for obvious privacy concerns. It's necessary for there to be explicit user consent before screen sharing.

> Also anyway we can skip the top portion of the browser with URL from being recorded ?

I'm not exactly sure what you mean by this. Could you elaborate and/or include a screenshot? Right now, the recording options are either your entire screen, a specific application window, or a specific tab.

**Comment by vinuvvk88** [comment]
@carsonsaldanha 

What I meant is - right now the recorder is a two-step process. First, we need to select the screen and then only it fires the recorder API internally to capture the screen.

What if I need to directly integrate this app with my web app, can I just place a "Record" button, and on clicking this, it should record the screen on my web app only. There shouldn't be any pop up for selecting screen.

To the other part, I meant, can I record only the content of the tab by ignoring the address bar and other things of the browser.

**Comment by carsonsaldanha** [comment]
Yeah, as I said before, the screen capture web API won't let you do this.
The only way to start a capture is to bring up the screen selector pop-up.
This is by design for privacy concerns to prevent websites from recording a
user's screen without them realizing they granted the permission.

As for recording just the content of a tab, there should be an option to
select a specific tab in the screen selector pop-up. Is the option not
showing up for you?
